# ==================================================
# CONFIGURAÇÃO DO SERVIDOR
# ==================================================
spring.application.name=baozi-store-api

# ==================================================
# CONFIGURAÇÃO DO POSTGRESQL
# ==================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/baozi_store
spring.datasource.username=postgres
spring.datasource.password=admin1531

# ==================================================
# JPA / HIBERNATE
# ==================================================
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG

# ==================================================
# DIALETO
# ==================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect