# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Configuração do Servidor
spring.application.name=baozi-store-api

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Configurção de conexão com o banco de dados PostegreSQL
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring.datasource.url=jdbc:postgresql://localhost:5432/baozi_store
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# JPA / HIBERNATE
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Atualiza automaticamente o esquema do banco de dados conforme as entidades JPA
spring.jpa.hibernate.ddl-auto=update

# Exibe as consultas SQL geradas pelo Hibernate no console
spring.jpa.show-sql=true

# Formata o código SQL exibido no console para facilitar a leitura e debug
spring.jpa.properties.hibernate.format_sql=true

# Define o nível de log para detalhamento das execuções do Hibernate
logging.level.org.hibernate.SQL=DEBUG

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Dialeto PostgreSQL para o Hobernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect