@startuml

title Baozi Store API - Diagrama de Caso de Uso\nMagno Ferreira4758995

left to right direction

actor "Usuário da API" as Usuario

rectangle "Baozi Store API" {

    rectangle "CLIENTE" as Cliente {
        usecase "Criar Cliente" as C1
        usecase "Listar Clientes" as C2
        usecase "Consultar Cliente por ID" as C3
        usecase "Atualizar Cliente" as C4
        usecase "Excluir Cliente" as C5
    }

    rectangle "PRODUTO" as Produto {
        usecase "Criar Produto" as P1
        usecase "Listar Produtos" as P2
        usecase "Consultar Produto por ID" as P3
        usecase "Atualizar Produto" as P4
        usecase "Excluir Produto" as P5
    }

    rectangle "PEDIDO" as Pedido {
        usecase "Criar Pedido" as PD1
        usecase "Listar Pedidos" as PD2
        usecase "Consultar Pedido por ID" as PD3
        usecase "Atualizar Pedido" as PD4
        usecase "Excluir Pedido" as PD5
    }
}

' ==========================
' RELACIONAMENTOS
' ==========================

Usuario --> C1
Usuario --> C2
Usuario --> C3
Usuario --> C4
Usuario --> C5

Usuario --> P1
Usuario --> P2
Usuario --> P3
Usuario --> P4
Usuario --> P5

Usuario --> PD1
Usuario --> PD2
Usuario --> PD3
Usuario --> PD4
Usuario --> PD5

@enduml